### ISSUE TITLE
Client Installation Fails

### ISSUE THREAD

**Issue by emb3dded** [fayaaz/spacewalk.ansible#1]
When installing the Client, it fails with the following error:
`FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.hostvars.HostVars object' has no attribute 'spacewalk'`

**Comment by fayaaz** [comment]
Looks like someone has continued the work on this.

https://github.com/redbeard28/ansible_role_spacewalk
